services:
  saharawi-db:
    container_name: saharawi-db
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - sahraoui-odoo

  saharawi-odoo:
    container_name: saharawi-odoo
    # build: .
    image: odoo:18.0-20250415
    depends_on:
      - saharawi-db
    ports:
      - "18069:8069"
    environment:
      DATABASE: ${DATABASE}
      HOST: ${DB_HOST}
      PORT: 5432
      USER: ${DB_USER}
      PASSWORD: ${DB_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf:ro
      - ./addons:/mnt/extra-addons
    networks:
      - sahraoui-odoo
      - nginx-proxy

volumes:
  odoo-db-data:
  odoo-web-data:

networks:
  sahraoui-odoo:
    driver: bridge
  nginx-proxy:
      external: true
